name: Run Script on Dispatch

on:
  repository_dispatch:
    types: [run-script]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run print_hello.sh
        run: ./print_hello.sh
