name: Run Script on Dispatch

on:
  repository_dispatch:
    types: [run-script]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print payload info
        run: |
          echo "Triggered by: ${{ github.event.client_payload.source }}"

      - name: Run print_hello.sh
        run: ./print_hello.sh
