name: Trigger Script from Webhook
on: repository_dispatch
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      WEBHOOK_PAT: ${{ secrets.WEBHOOK_PAT }}
    steps:
      - name: Checkout repo1
        uses: actions/checkout@v2

      - name: Verify PAT Before Execution
        run: |
          if [[ -z "$WEBHOOK_PAT" ]]; then
            echo "Missing authentication token! Exiting..."
            exit 1
          fi
          echo "Authentication token verified successfully!"

      - name: Execute print_hello.sh
        run: ./print_hello.sh
